### ISSUE TITLE
RGI05 (Greenland) issue with rock outcrops

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#11]
Should be same as RGI6 for most, except some outlines in NE submitted by Philipp. [trello card](https://trello.com/c/FcGTlTNe).

**Known issues in RGI7a**:

- large discrepancies in rock outcrops, missing from GLIMS. Need to check if this is a GLIMS issue or a GLIMS to RGI formatting problem.

![image](https://user-images.githubusercontent.com/10050469/131521173-d7d56c51-81ca-4fec-9849-cc2d062c0103.png)

**Comment by fmaussion** [comment]
@bruceraup I can confirm that GLIMS viewer does have outcrops from RGI which are not in GLIMS. E.g.:

![image](https://user-images.githubusercontent.com/10050469/131733707-8a1bf5d5-7ae7-461c-99f7-371bf07c94cc.png)

I can pinpoint these with my script. The list of glaciers affected is quite long (894). Let me know if you need them.

**Comment by fmaussion** [comment]
Her is another (clearer) example. I think that the rock outcrop outline is shown in green because it is in RGI, but not in GLIMS. @bruceraup , what are the red filled geometries by the way?

![image](https://user-images.githubusercontent.com/10050469/140084027-10da22f7-a0a4-4da0-89dc-57843fd5dce9.png)

**Comment by bruceraup** [comment]
Red geometries are internal rocks (nunataks).

**Comment by fmaussion** [comment]
Thanks! I guess this means that the green one didn't make it to GLIMS?

**Comment by fmaussion** [comment]
Trello card: https://trello.com/c/O5g9DAbT

**Comment by fmaussion** [comment]
Now solved in GLIMS
