### ISSUE TITLE
RGI03 (Arctic Canada, North)

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#15]
We use:
- GLIMS subm_id 635: seven glaciers on Melville Island, outlines from 1988 From Berthier et al (RGI6 outlines for Melville are not available in GLIMS)
- GLIMS subm_id 728: Copland, Luke; Kochtitzky, William et al - Central Ellesmere + West
- GLIMS subm_id 723: Paul, Frank; Rastner, Philipp; White, Adrienne - North Ellesmere
- GLIMS subm_id 590: RGI6 elsewhere

![image](https://user-images.githubusercontent.com/10050469/144325887-3bb695d2-1eb2-4aff-bd94-26b5aa1d7a73.png)

**Possible other choices**:
- use subm_id 660, 661 for Melville (aydhisudhiwongs, Pim; Raup, Bruce H. 2017) 

**Known issues**:
- none yet! 

**Links:**:
- data: https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l3_rgi7a_tar/RGI03.tar.gz
- all GLIMS inventories: https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l0_tmp_data/rgi03_inventories.tar.gz
- executed notebook: https://nbviewer.jupyter.org/urls/cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_scripts/workflow/RGI03.ipynb

**Comment by fmaussion** [comment]
@willkochtitzky are you the author of the green outlines in the map above (ID 728), and would you mind sharing the original data with me?

Do you know if by any chance someone also worked on the Devon ice caps "ugly" neighbor on the West? It is looking wierd and is missing divides...

**Comment by willkochtitzky** [comment]
Hi Fabien, yes I made the outlines in green. I have attached them here (the ones I sent to Bruce). I don't know anyone who is working on the outlines to the west, but I would be happy to do that and send it in as well. I could do that next week if that would be useful.

[ACN_update_3Sep2021.zip](https://github.com/GLIMS-RGI/rgi7_scripts/files/7644035/ACN_update_3Sep2021.zip)

**Comment by fmaussion** [comment]
Thanks for sharing the data!

> but I would be happy to do that and send it in as well

I don't know how much work that would be. All the outlines west of devon ice cap look very weird and any attempt to make it better surely is useful (but not mandatory, as this has been in RGI "as is" for a while now):

![image](https://user-images.githubusercontent.com/10050469/144485771-7c80ad00-4e77-4bf3-8c1d-602d963f2fa4.png)

**Comment by willkochtitzky** [comment]
All of Devon Island needs some work. If you notice just on the NE side of your red circle there is one RGI polygon but at least 4 termini of this glacier, so that needs work as well. Perhaps it is best to leave this as is for now in RGI7, but I will put it on my to do list in the next few years to update this and submit it to GLIMS. I would really like to do a new inventory of Arctic Canada North glaciers, so this would be a good outcome of that project. Would this be ok with you?

**Comment by fmaussion** [comment]
Yes, of course! Thanks a lot.

**Comment by fmaussion** [comment]
I moved these regional descriptions to the wiki where it is better organized: https://github.com/GLIMS-RGI/rgi7_scripts/wiki/RGI03-(Arctic-Canada,-North) 

I'll open a new issue with your comments for RGI7.1 ;-)
