### ISSUE TITLE
RGI10 (North Asia)

### ISSUE THREAD

**Issue by burnout-stephl** [GLIMS-RGI/rgi7_scripts#2]
RGI7a for region 10 was produced by:
1) extracting RGI6 data from GLIMS data base
2) dropping all nominal glaciers (116, located on Wrangel Island and islands in the Sibirian Sea) 
3) replacing glaciers in Kamtchatka with data by Barr

points to discuss are:
- omitted nominal glaciers which account for about 84 km² and could not be replaced by other data as no outlines for these areas are available in GLIMS.
- the subset of Kamchatka glaciers which shall be replaced based on data by Barr. In a first version we replaced all...
- the glacier divides presented by Barr which should be checked and eventually be revised.

**Comment by fmaussion** [comment]
Thanks! This region also seem to have ~ 10 glaciers which are merged as in https://github.com/GLIMS-RGI/glims_issue_tracker/issues/5

**Comment by willkochtitzky** [comment]
Are you guys talking about the nominal glacier in the Delong Islands? I have attached a picture here. I know this was also a problem in RGI6 with the circles, now they are missing. If it would be useful, I would be happy to digitize these glaciers and submit them to GLIMS next week.
<img width="583" alt="Screen Shot 2021-07-21 at 11 33 35 AM" src="https://user-images.githubusercontent.com/30648918/126517169-2f06e546-639f-4dc9-81c6-57ba554633ec.png">

**Comment by bruceraup** [comment]
There are "nominal" (circles representing) glaciers on Wrangell Island also.

**Comment by willkochtitzky** [comment]
Ah, I had not noticed that before. Are there even glaciers on Wrangell Island? I see the circles now in RGI6, but I don't ever remember seeing glaciers on Wrangell before in Landsat imagery, but maybe I am not looking closely enough. Maybe hard to tell the difference between perennial snow and glaciers here? Regardless, I am happy to dive into this and generate the best outlines I could for both of these areas. Would that be helpful? I just don't want to duplicate work someone else is already doing. @bruceraup, are there other areas where there are still circle glaciers? If so, I am happy to generate these layers too to make sure RGI7 is as complete as possible.

**Comment by fmaussion** [comment]
Thanks a lot @willkochtitzky for this.

Unfortunately, the two main actors here (Frank and Philipp) are not using github. Can you send them an email linking to this issue and discuss with them whether new mapping is necessary? (I believe it will be - in general I would suggest not having nominal glaciers in GLIMS at all, so these need to be replaced or deleted if there are no glaciers there, no?)

**Comment by willkochtitzky** [comment]
Hi Fabien, will do.

**Comment by fmaussion** [comment]
What is the status of this, after the email conversation? Are there outlines to be added to GLIMS or RGI?

**Comment by willkochtitzky** [comment]
Apologies for not closing the loop here. Here is the link to the outlines: https://www.dropbox.com/sh/6riifept2whk7gs/AABiSDc6fzLBbFiX54VNZGWna?dl=0
I sent them to Bruce on July 23, I received confirmation that he got them but not that they were ingested.

**Comment by fmaussion** [comment]
Thanks will! I had a look at the outlines: in principle we will take them "as is" for RGI (because it is better than no glaciers), however to be optimal they should have ice flow divides. For now we will keep them as is, unless you have a quick way to compute the flow divides.

**Comment by willkochtitzky** [comment]
I don't have a cleaver way of doing it, but I could go do it manually for these glaciers, it is not many. I could also do that next week and resubmit them if that would be useful. I didn't fully understand how these divides worked in RGI until speaking with Frank last week. So I am happy to learn more about the process!

**Comment by fmaussion** [comment]
Thanks OK I understand. Wait before doing anything here, let's see if Philipp can help

**Comment by fmaussion** [comment]
On top of that, email from Tatiana (31.08) with suggestions for improvement.

**Comment by fmaussion** [comment]
I think this has now been including in GLIMS submission 726 and is now in RGI7a: https://github.com/GLIMS-RGI/rgi7_scripts/wiki/RGI10-(North-Asia)

Reopen if I'm mistaken
