### ISSUE TITLE
RGI12: difference between version in GLIMS and final version by Levan

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#28]
There is a tiny difference between the glims version and the final inventory by Levan for three outlines. Email by Levan:

This error is due to different views on the definition of the margins of the Garabashi Glacier.

While working on our preprint, I was advised by Russian colleagues to modify the margins of Garabashi Glacier (and thus Azay and Terskol as neighbouring glaciers) before submitting to Zenodo. Mind you, that the database was already submitted to GLIMS at that time .

The Russian colleagues considered it important to keep the glacier boundaries in our Zenodo database consistent with in-situ measurements because Garabashi is one of the representative glaciers in the WGMS and this will be important for future comparisons (e.g. glaciological mass balance vs geodetic one).

To conclude, the outlines of Garabashi, Azay, and Terskol glaciers are more comprehensive in Zenodo (see attached) than those in GLIMS. However, the rest of the glaciers in both databases are the same.

I know, this sounds a bit annoying, but perhaps Bruce wants to replace them in GLIMS database as well? If so, I'm attaching the shp file of just those three glaciers. Sorry Bruce about it, but this was not only my fault :) and thank you Fabien again for pointing this out.

![image](https://user-images.githubusercontent.com/10050469/146206349-df81d4d4-9d3e-4086-96c2-bc0871173fdf.png)

**Comment by LevanTielidze** [comment]
- Since you are already familiar with this issue, this is just a simple reminder that these three glacier polygons (Azay, Garabashi, and Terskol) still need to be replaced in the RGI7 database according to the Zenodo database. This should be also amended in GLIMS.
- The rest of the outlines from the Greater Caucasus looks good to me. Note that I haven't checked the outlines from the Middle East sub-region.
- Other minor changes: the "analysts" should be "Tielidze, Levan and Paul, Frank". Currently, it is only "Tielidze, Levan".

**Comment by fmaussion** [comment]
Thanks @LevanTielidze !  The two issues you mention (outlines to be replaced and analysts to be added) need to be done upstream in GLIMS - @bruceraup and I know about this, and will make sure that this is updated before the final release. 

Regarding the outlines from the rest of RGI12, we are not yet aware of anyone reviewing them, we have just taken them from RGI version 6. If you have time to spare, this would of course be a welcomed contribution, but only if this fits your schedule!

**Comment by LevanTielidze** [comment]
Thanks, @fmaussion . I started looking at the glacier outlines of the Middle East based on the Landsat 2000 archive, and there is an absolute mess (especially in Iran). I will review/re-digitize this in detail and provide my report over the next few weeks. Definitely before the 20th of January.

**Comment by fmaussion** [comment]
Thanks @LevanTielidze! Is noted, thanks a lot for your work

**Comment by LevanTielidze** [comment]
Thanks again, @fmaussion . I just sent the revised dataset and word document in a separate email.

**Comment by fmaussion** [comment]
I think this is now corrected! @LevanTielidze if you want to check: https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l3_rgi7a_tar/RGI12.tar.gz
