### ISSUE TITLE
RGI16: Cotopaxi RGI6 outline is not in GLIMS

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#30]
The red outline (in GLIMS) is actually from the RGI submission ID (i.e. it should be from RGI), but the outline is different.

A look at the RGI technical document explains it: GLIMS probably ingested RGI5:

![image](https://user-images.githubusercontent.com/10050469/146646988-65a2a579-b67c-4e44-aa29-018d4f95d1a3.png)

![image](https://user-images.githubusercontent.com/10050469/146646836-4d54c850-3bd8-4de4-be8d-7cde10853125.png)

**Comment by fmaussion** [comment]
Here is the outline for ingest: [Cotopaxi_update.tar.gz](https://github.com/GLIMS-RGI/rgi7_scripts/files/8515268/Cotopaxi_update.tar.gz)

**Comment by bruceraup** [comment]
So, the RGI5 outline should be *removed* from GLIMS?  That is, was it deemed to be incorrect?  I take it that it was, since the area apparently grew by 24% from 1997 to 2000, based on the data.  Just want to double-check.

**Comment by fmaussion** [comment]
Yes I'm not sure either about where the RGI5 outline came from. Graham seem to have decided that the RGI6 outline is more accurate.

**Comment by bruceraup** [comment]
Okay, I'm on this now.

**Comment by bruceraup** [comment]
This re-ingest is done.  New submission_id is 753.

**Comment by fmaussion** [comment]
Checked! It worked
