### ISSUE TITLE
RGI16: Mt Kibo outline is weird in GLIMS

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#31]
![image](https://user-images.githubusercontent.com/10050469/146647052-a8d56f16-a5ad-4a03-ae32-8eaf7e3ae5f9.png)

This is glac_id G037344E03080S, alsys_id 309545

**Comment by fmaussion** [comment]
Here is the file from RGI6:

[Kibo_outline.tar.gz](https://github.com/GLIMS-RGI/rgi7_scripts/files/8512531/Kibo_outline.tar.gz)

**Comment by fmaussion** [comment]
Link to trello: https://trello.com/c/3jOqgxHY

**Comment by fmaussion** [comment]
@bruceraup submission ID 754 still has the same issues - something must be wrong with the original outline that GLIMS does not like at all.

**Comment by bruceraup** [comment]
Should be fixed now!

**Comment by fmaussion** [comment]
Checked - and it is now correct! Thanks!
