### ISSUE TITLE
Missing glacier in RGI4 - Arctic Canada South

### ISSUE THREAD

**Issue by willkochtitzky** [GLIMS-RGI/rgi7_scripts#35]
<img width="1119" alt="Screen Shot 2021-12-22 at 1 06 12 PM" src="https://user-images.githubusercontent.com/30648918/147136341-17713b89-b9d1-45a9-beef-240cbfd2756e.png">
It looks like this glacier was cut out at some point, but I am not sure why. This is located approximately at 71.54°N, 74.48°W.

Does this outline already exist somewhere else? I checked GLIMS and I don't see an outline there for it. But maybe someone has it somewhere? If not, I can digitize it, but it will require correction of the main tidewater glacier here too.

**Comment by fmaussion** [comment]
@willkochtitzky thanks a lot - I believe this may happem


RGI04 is currently in complete remapping by Frank and Philipp (https://github.com/GLIMS-RGI/rgi7_scripts/wiki/RGI04-(Arctic-Canada,-South): if you agree, we will ask you to review their work when available (by January)

**Comment by willkochtitzky** [comment]
No problem! Happy to do that and help any other way I can. Glad to hear they are working on this!

**Comment by fmaussion** [comment]
@willkochtitzky here is the new data for RGI04: https://cluster.klima.uni-bremen.de/~fmaussion/misc/rgi7_data/l3_rgi7a_tar/ 

Would you mind checking it? I'm confident that they should be better.

**Comment by willkochtitzky** [comment]
@fmaussion I just forwarded you and email chain that Frank and I had about these outlines (I think we are talking about the same ones). Happy to look again, but I might have already done this for Frank.

**Comment by willkochtitzky** [comment]
Sounds good!
