### ISSUE TITLE
RGI09 (Russian Arctic): wrong ice divide on one tidewater glacier 

### ISSUE THREAD

**Issue by willkochtitzky** [GLIMS-RGI/rgi7_scripts#4]
<img width="1012" alt="Screen Shot 2021-07-22 at 2 48 24 PM" src="https://user-images.githubusercontent.com/30648918/126692990-9fe61ecb-90ab-4c8b-bc47-d89bd045a622.png">
I am not sure if this is a big enough issue to merit our time in fixing. I came across this because the mass balance budgets are way off, I think due to the size of the glacier in RGI. 
In RGI7 it is: G059108E75722N
In RGI6 it is: RGI60-09.00088

I drew the red arrow where I think you have flow coming into this basin. I am not sure how to redo the basin boundaries, just that this one looks way too small based on the size of the calving front and crevasses/velocity. If there is a suggestion for how to fix it, I am very happy to do the work to make it happen.

This is the ID for the Landsat image used here: LE07_L1TP_179006_20000812_20170210_01_T1
From August 12, 2000

**Comment by fmaussion** [comment]
Thanks! In terms of workflow (what needs to be done), the easiest would be to select the two or three entities in GLIMS that need change and change only these. These could then be submitted to GLIMS as a new contribution, and in the script we could unambiguously replace the three faulty ones with the new contribution.

**Comment by willkochtitzky** [comment]
Excellent, I will do this and resubmit to GLIMS next week.

**Comment by fmaussion** [comment]
Actually, did you submit anything related to this issue @willkochtitzky ?

**Comment by willkochtitzky** [comment]
I actually never did. I wasnt sure if it was really helpful or just extra work. If it is helpful, I could do that this afternoon.

**Comment by willkochtitzky** [comment]
See attached for the corrected outlines (also emailed to @fmaussion and Bruce).
This impacts RGI6 glaciers: 
RGI60-09.00088
RGI60-09.00060
RGI60-09.00057

No other glaciers will be impacted, I left the other borders the same as they are pretty close.

[NZ_1Sep2021.zip](https://github.com/GLIMS-RGI/rgi7_scripts/files/7093452/NZ_1Sep2021.zip)

**Comment by fmaussion** [comment]
Trello card: https://trello.com/c/LXovmAfk

**Comment by fmaussion** [comment]
Just to keep track of this: I will incorporate them in RGI7 with a temporary workaround but there is some issues to be fixed in GLIMS before I can close this. cc @bruceraup
