### ISSUE TITLE
RGI16 (Low Latitudes SA) outlines can be removed (A. Rabatel)

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#44]
Here is his review:

---
Small snow patches that according to me are not glaciers (nor glacierets).

The following can be removed:

[edited: see file attached]

[removed_ar.csv](https://github.com/GLIMS-RGI/rgi7_scripts/files/7980808/removed_ar.csv)

**Comment by fmaussion** [comment]
@bruceraup I changed the list of IDs to a text file. There are 131 to remove.

Associated trello card: https://trello.com/c/H2AN5CuD

**Comment by bruceraup** [comment]
I have removed the data from GLIMS for these analysis IDs.  If someone can review the result, I'd appreciate it.  --Bruce
