### ISSUE TITLE
Khumbu and other glaciers in the Everest region

### ISSUE THREAD

**Issue by tbolch** [GLIMS-RGI/rgi7_scripts#50]
I checked the updated outlines for the Khumbu region and tend to disagree with the outlines of the termini. It is clearly very challenging to identify the correct margin of these debris-covered glaciers and I understand the criteria applied by Akiko, but I would add some more parts, in particular for Khumbu.  
See the comparison of the outlines I used in Bolch et al. 2011, TC (red) and Sakai (black). The DEM differencing results (e.g. SRTM vs. HMA DEM from King et al. 2019, Sci Rep) show that ice loss would be missed if the outlines from Sakai would be used. As the Khumbu region is well known and these glaciers heavily studied, I think these outlines should be discussed and adjusted for 7.0.
![ReviewKhumbu04](https://user-images.githubusercontent.com/99332058/153255376-a23f3845-0511-40a5-91d7-5d3d8abbc14a.jpg)
![ReviewKhumbu05](https://user-images.githubusercontent.com/99332058/153255396-d05761a8-41e6-4a7e-9268-672dfa79c837.jpg)

**Comment by bruceraup** [comment]
Data received from Tobias. I will need info on imagery and methods to ingest, however.

**Comment by fmaussion** [comment]
This is now in RGI7a! Thanks all
