### ISSUE TITLE
RGI19: many Islands are poorly georeferenced

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#61]
This is most notable when checking them against topography, here example of Pine Island Bay:

![image](https://user-images.githubusercontent.com/10050469/179740503-6138ae61-5104-4201-8924-0926aff72e53.png)

**Comment by fmaussion** [comment]
What's striking here of course is that the various datasets dont agree...

**Comment by eberthie** [comment]
I would be happy to check the problematic Island in Antarctica using the SPOT5 images that were acquired during IPY during the SPIRIT project. But I leave tomorrow... I could check when I come back from vacations 16 August. (I did not promise anything, OK ?) Do you have already a list of the Islands that deserve specific attention?

**Comment by fmaussion** [comment]
> I could check when I come back from vacations 16 August. (I did not promise anything, OK ?) 

No problem - we are a free-work shop ;-) 

> Do you have already a list of the Islands that deserve specific attention?

Unfortunately no. But I think I could have a student (@afisc) help you out because we notice mostly when we try to project DEM onto it. The regions with very poor coverage here are good indicators: https://rgitools.readthedocs.io/en/latest/dems_subregions.html#antarctic-and-subantarctic

**Comment by iamdonovan** [comment]
Most likely it's an issue with the georeferencing/orthorectification of the underlying images - a number of these have BgnDate/EndDate values in the 1970s, which makes me think air photos or topographic maps.

**Comment by fmaussion** [comment]
Yes georeferencing definitely. The example of `RGI60-19.01405` above is particularly weird, because "old" DEM products (RAMP, DEM3) agree with the outlines, while the recent ones do not...

**Comment by iamdonovan** [comment]
But that would make sense, if the "old" DEM products are based off of topographic maps? Either that, or the island is actually just a massive grounded iceberg. :)
