### ISSUE TITLE
19-03: Subantarctic (Atlantic) 

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#66]
This region has presently two inventories available:
- 700 Castro, Gargantini, Gimenez, Hidalgo, Masiokas... 
- 585 RGI6

The two datasets have issues. RGI6 seems better on South Georgia where the 700 datasets have weird glacier separation issues and mapped snow and missed debris cover (purple: 700, green, RGI6)

![image](https://user-images.githubusercontent.com/10050469/206910659-658c64ba-6a7a-4db2-b66a-f032602d8fcf.png)

In the South Sandwich Islands, 700 seems to be of much better quality.

On Bouvet Island, only RGI6 is available and is OK but a bit shifted:

![image](https://user-images.githubusercontent.com/10050469/206903694-df360cc7-5cfb-4293-a959-303c94b28b71.png)

**Comment by fmaussion** [comment]
Therefore, current situation is: 

![image](https://user-images.githubusercontent.com/10050469/207267006-c799d5c8-50d3-4063-9dd8-94aede1877c2.png)

**Comment by willkochtitzky** [comment]
@fmaussion I just sent the outlines of Bouvet Island to Bruce for GLIMS. see attached here as well. I did not address the other issue you point out here.
[15Dec22_outlines_Bouvet_Island.zip](https://github.com/GLIMS-RGI/rgi7_scripts/files/10239890/15Dec22_outlines_Bouvet_Island.zip)

**Comment by fmaussion** [comment]
In RGI7. Thanks!
