### ISSUE TITLE
Glacier complex product with precision model?

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#74]
Sometimes the glacier complex product looks like this:

![image](https://github.com/GLIMS-RGI/rgi7_scripts/assets/10050469/ae9cfb79-6356-47f5-b056-236e218c433b)

if you zoom in, you see that the outlines are "close", but not quite:

![image](https://github.com/GLIMS-RGI/rgi7_scripts/assets/10050469/5881a882-ef29-476b-93c7-7189b64c7733)

Maybe this can be solved with a precision model, maybe not...

**Comment by iamdonovan** [comment]
I think this should be possible using [shapely.ops.snap()](https://shapely.readthedocs.io/en/stable/manual.html#snapping), right?

**Comment by fmaussion** [comment]
I did not know about this, that's great! It looks like one needs to identify the two geometries to snap first, which suggests we should do it on all the geometries even if they don't need it. That's probably okay.

So the workflow would be:
- to the standard dissolve (already happening)
- identify the glacier geometries in each new glacier complex (already done for the RGI product, so that users know which glaciers have been merged)
- for all geometries in a cluster, snap them one by one to the first one with a chosen tolerance

I think this might help with case 1 (green in the picture below) but it still wont solve 2 (red in the picture below) where there is no way to know that the two geometries are so close. The red circle case would imply adding a 4th step which looks for nearby geometries if they can be snapped, but this looks tedious and error prone...

Thoughts?


![image](https://github.com/GLIMS-RGI/rgi7_scripts/assets/10050469/4417af21-1952-4f5e-a3fb-6a8c998198e7)

**Comment by fmaussion** [comment]
Snap did not work well :laughing: 

![image](https://github.com/GLIMS-RGI/rgi7_scripts/assets/10050469/26eb7401-9f3e-4b50-a139-6286a0e2edca)

Issue now reported here, wont be fixed in RGI7: https://github.com/GLIMS-RGI/rgi_issue_tracker/issues/21
