### ISSUE TITLE
RGI03 (Arctic Canada, North)

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi7_scripts#9]
RGI6 can be reproduced with some issues (manual edits which seem better in RGI most of the times - ~ 30 glaciers are affected, but all searchable in script). 

Whether this needs a change in GLIMS or not is to be reassessed after the new outlines from @willkochtitzky have been ingested into GLIMS.

Will's outlines on top of RGI6:

![image](https://user-images.githubusercontent.com/10050469/131507415-31fed778-35f4-4558-9e2e-a87e63e9652e.png)

This should be easy to replace in RGI7 with some regional masks (where to keep RGI6 and where not).

TODO Fabien: any other dataset to be expected?

**Comment by willkochtitzky** [comment]
Let me know if there is anything I can do to help. I don't have any other datasets to submit here. Luke had a PhD student from a few years ago make excellent outlines for Northern Ellesmere. Frank had these outlines and was making new ones, but was going to check with Luke about that. Those should be updated in RGI7 as they are a huge improvement. I am not sure the status of that or if they are currently included in this or not, but the RGI6 outlines for Northern Ellesmere are not good.

**Comment by fmaussion** [comment]
Northern Ellesmere outlines have been submitted by Frank last week.

**Comment by fmaussion** [comment]
Closed in favor of https://github.com/GLIMS-RGI/rgi7_scripts/issues/15 (almost done)
